ConfigPort = 8080
RProxyConfigPort = 8081
RProxyListenAddress = "127.0.0.1"
RProxyBin = "./rproxy"

COAPPort = 5000
HTTPPort = 8000
GRPCPort = 9000

Backend = "docker"
ID = "cloud"

Mode = "cloud"

RegistryPort = 8082
Host = "localhost"
