ConfigPort = 8380
RProxyConfigPort = 8381
RProxyListenAddress = "127.0.0.1"
RProxyBin = "./rproxy"

COAPPort = 5300
HTTPPort = 8300
GRPCPort = 9300

Backend = "docker"
ID = "edge_a"

Mode = "edge"

RegistryPort = 8382
Host = "localhost"
ParentAddress = "localhost:8282"